# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "non_repeating", # <set_colnames>
  "space_count", # <indentation_to_variables>
  "counter", # <indentation_to_variables>
  "space_group", # <indentation_to_variables>
  "value", # <indentation_to_variables>
  "indent_level", # <indentation_to_variables>
  "variable_label", # <indentation_to_variables>
  ":=", # <indentation_to_variables>
  "value2", # <indentation_to_variables>
  "nbsp_count", # <strip_indentation>
  "counter", # <strip_indentation>
  "nbsp_group", # <strip_indentation>
  "indent_level", # <strip_indentation>
  "indent_level_rev", # <strip_indentation>
  "variable_label", # <strip_indentation>
  "value", # <strip_indentation>
  "variable_label0", # <strip_indentation>
  "variable_level", # <strip_indentation>
  "group1_level", # <separate_bign>
  NULL
))
