#' Remove empty rows
#'
#' This function removes empty rows (where all cells are empty strings) inside a
#' data frame generated by calling [rtf_to_html()].
#'
#' @param data A data frame generated by calling [rtf_to_html()].
#'
#' @return A data frame with empty rows removed.
#'
#' @keywords internal
strip_empty_rows <- function(data) {
  filter(data, !if_all(everything(), ~ . == ""))
}

#' Remove the header
#'
#' This function removes the rows representing a header (e.g., titles and
#' subtitles) inside a data frame generated by calling [rtf_to_html()].
#'
#' @param data A data frame generated by calling [rtf_to_html()].
#'
#' @return A data frame with the header removed.
#'
#' @keywords internal
strip_header <- function(data) {
  # The second+ columns are populated with empty strings "" alongside the
  # header information which can be used to determine the row indices of the
  # header:
  header_last_row <- min(which(data[[2]] != "" | is.na(data))) - 1

  # Some tables repeat across pages in the original RTF. This results in
  # data frames containing combined data frames with headers that repeat across
  # several points. Capture the original header:
  header <- slice(data, 1L:header_last_row)

  # Remove all copies of the header:
  data |>
    anti_join(header)
}

#' Remove the footer
#'
#' This function removes the rows representing a footer inside a data frame
#' generated by calling [rtf_to_html()].
#'
#' @param data A data frame generated by calling [rtf_to_html()].
#'
#' @return A data frame with the footer removed.
#'
#' @keywords internal
strip_footer <- function(data) {
  # The last row in the third column that is not an empty string signals the
  # last row before the footer. All following rows until the end of the data
  # frame are populated with empty strings alonside the footer values in
  # the first column. We also need an escape hatch in this instance the table
  # only has two columns:
  col_index <- if (ncol(data) >= 3) 3 else 2
  footer_first_row <- max(
    which(
      data[[col_index]] != "" | is.na(data[[col_index]])
    )
  ) +
    1

  # Some tables repeat across pages in the original RTF. This results in
  # data frames containing combined data frames with footers that repeat across
  # several points. Capture the original footer:
  footer <- slice(data, footer_first_row:nrow(data))

  # Remove all copies of the footer:
  data |>
    anti_join(footer)
}

#' Remove repeat column names
#'
#' This function removes columns names that repeat across multiple rows (caused
#' by pagination in the original RTF files) inside a data frame generated by
#' calling [rtf_to_html()]. Only the first occurance should be kept.
#'
#' @param data A data frame generated by calling [rtf_to_html()].
#'
#' @return A data frame with the repeat column names removed.
#'
#' @keywords internal
strip_repeat_colnames <- function(data) {
  # This assumes column names are in the first row (which is the case if this
  # function is called after calling `strip_header()`)
  first_row <- dplyr::slice(data, 1L)
  remaining_rows <- dplyr::slice(data, -1L)

  remaining_rows_without_colnames <- remaining_rows |>
    dplyr::anti_join(first_row)

  dplyr::bind_rows(first_row, remaining_rows_without_colnames)
}

#' Set column names
#'
#' This function sets columns names inside a data frame generated by calling
#' [rtf_to_html()]. It assumes the first row contains the actual column names.
#'
#' @param data A data frame generated by calling [rtf_to_html()].
#'
#' @return A data frame with the repeat column names removed.
#'
#' @keywords internal
#' @autoglobal
set_colnames <- function(data) {
  # This assumes column names are in the first row (which is the case if this
  # function is called after calling `strip_header()`)
  colnames <- slice(data, 1L) |> as.character()

  # For any missing column names, it is assumed that the missing column can be
  # found on the first row of the corresponding column where all other columns
  # are empty strings.
  colnames_missing_indices <- which(colnames == "")

  x_counter <- 1
  for (i in colnames_missing_indices) {
    filtered <- filter(non_repeating, if_all(!i, ~ .x == ""))
    if (nrow(filtered != 0)) {
      replacement <- filtered |>
        slice(1L) |>
        pull(i)
    } else {
      replacement <- paste0("X", x_counter)
      x_counter <- x_counter + 1
    }
    colnames[i] <- replacement
  }

  data |>
    rename_with(~colnames) |>
    slice(-1L)
}

#' Strip empty columns
#'
#' Remove any columns where all values are NA or empty strings.
#'
#' @keywords internal
strip_empty_cols <- function(data) {
  data |>
    select(where(~ !all(is.na(.)))) |>
    select(where(~ !all(. == "")))
}

#' Strip pagination from a table
#'
#' This function combines the functionality of [strip_empty_rows()],
#' [strip_empty_cols()], [strip_header()], [strip_footer()],
#' [strip_repeat_colnames()], and [set_colnames()] into a single function. If
#' fine grained control is not required to remove certain elements of a table,
#' this function is preferred because the actions of stripping table elements
#' are dependent on each other (e.g., to remove repeat column names, we first
#' must identify these by stripping the header).
#'
#' When pages share the same column structure, the single-structure path is
#' used (anti-join approach). When pages cycle between different column
#' structures (e.g., different treatment groups on alternating pages), the
#' multi-structure path splits pages, joins them by row labels, and produces a
#' single wide dataframe.
#'
#' @param data A data frame generated by calling [rtf_to_html()].
#'
#' @return A data frame where pagination has been stripped.
#'
#' @keywords internal
strip_pagination <- function(data) {
  data <- strip_empty_rows(data)
  data <- strip_empty_cols(data)

  pages <- split_into_pages(data)

  if (length(pages) <= 1) {
    return(paginate_single_structure(data))
  }

  parsed_pages <- lapply(pages, parse_page)
  # Compare stat column signatures only (cols 2+), since col 1 header text

  # may differ across pages while the column structure is the same
  signatures <- vapply(
    parsed_pages,
    function(p) paste(p$colnames[-1], collapse = "|"),
    character(1)
  )

  if (length(unique(signatures)) == 1L) {
    return(paginate_single_structure(data))
  }

  paginate_multi_structure(parsed_pages, signatures)
}

#' Single-structure pagination (original algorithm)
#' @noRd
paginate_single_structure <- function(data) {
  header_last_row <- min(which(data[[2]] != "" | is.na(data))) - 1
  header <- slice(data, 1:header_last_row)

  col_index <- if (ncol(data) >= 3) 3 else 2
  footer_first_row <- max(
    which(
      data[[col_index]] != "" | is.na(data[[col_index]])
    )
  ) +
    1
  footer <- slice(data, footer_first_row:nrow(data))

  colnames <- slice(data, header_last_row + 1)

  table_cells <- data |>
    anti_join(header) |>
    anti_join(footer) |>
    anti_join(colnames) |>
    suppressMessages()

  non_repeating <- bind_rows(colnames, table_cells)

  colnames <- slice(non_repeating, 1L) |> as.character()
  colnames_missing_indices <- which(colnames == "")

  x_counter <- 1
  for (i in colnames_missing_indices) {
    if (i == 1) {
      colnames[i] <- " "
    } else {
      filtered <- filter(non_repeating, if_all(!i, ~ .x == ""))
      if (nrow(filtered != 0)) {
        replacement <- filtered |>
          slice(1L) |>
          pull(i)
      } else {
        replacement <- paste0("X", x_counter)
        x_counter <- x_counter + 1
      }
      colnames[i] <- replacement
    }
  }

  non_repeating |>
    rename_with(~colnames) |>
    slice(-1L) |>
    distinct()
}

#' Split a dataframe into per-page tibbles
#'
#' Detects repeated title rows (first cell matches row 1, all other cells
#' empty) and splits the data at each title row.
#'
#' @noRd
split_into_pages <- function(data) {
  title_text <- data[[1]][1]

  is_title <- data[[1]] == title_text &
    vapply(
      seq_len(nrow(data)),
      function(r) all(data[r, -1] == "" | is.na(data[r, -1])),
      logical(1)
    )

  title_rows <- which(is_title)

  if (length(title_rows) <= 1) {
    return(list(data))
  }

  page_starts <- title_rows
  page_ends <- c(title_rows[-1] - 1L, nrow(data))

  lapply(seq_along(page_starts), function(i) {
    slice(data, page_starts[i]:page_ends[i])
  })
}

#' Parse a single page into its components
#'
#' Extracts spanner labels, column names, and body rows from a single page.
#'
#' @noRd
parse_page <- function(page) {
  # Row 1 is the title
  # Spanner: rows where col1 is empty and col2+ has group labels
  # Find the colnames row: first row after title where col1 is not empty
  header_end <- 1L
  for (r in 2:nrow(page)) {
    row_vals <- as.character(page[r, ])
    if (row_vals[1] == "" || is.na(row_vals[1])) {
      header_end <- r
    } else {
      break
    }
  }

  # Spanner is rows 2:header_end (between title and colnames)
  spanner_raw <- if (header_end >= 2) {
    as.character(page[2, ])
  } else {
    rep("", ncol(page))
  }

  # Colnames row is right after the spanner block
  colnames_row_idx <- header_end + 1
  col_names <- as.character(page[colnames_row_idx, ])

  # Build spanner-to-column mapping using repeating stat groups.
  # Non-empty spanner labels (skipping col 1) mark group starts.
  # Stat columns (cols 2+) with non-empty colnames repeat in groups.
  spanner_labels <- spanner_raw[-1]
  stat_colnames <- col_names[-1]
  non_empty_spanner_idx <- which(spanner_labels != "" & !is.na(spanner_labels))
  non_empty_stat_idx <- which(stat_colnames != "" & !is.na(stat_colnames))

  spanner <- rep("", length(col_names))
  if (length(non_empty_spanner_idx) > 0 && length(non_empty_stat_idx) > 0) {
    # Determine group size: number of non-empty stat cols / number of spanner labels
    n_groups <- length(non_empty_spanner_idx)
    group_size <- length(non_empty_stat_idx) %/% n_groups

    if (group_size > 0) {
      for (g in seq_len(n_groups)) {
        label <- spanner_labels[non_empty_spanner_idx[g]]
        start_idx <- non_empty_stat_idx[((g - 1) * group_size) + 1]
        end_idx <- non_empty_stat_idx[g * group_size]
        # +1 offset because spanner/stat_colnames are 0-indexed relative to col_names
        spanner[(start_idx + 1):(end_idx + 1)] <- label
      }
    }
  }

  # Footer: last row where col1 has text and cols 2+ are empty
  footer_start <- nrow(page) + 1L
  for (r in nrow(page):1) {
    row_vals <- as.character(page[r, ])
    if (all(row_vals[-1] == "" | is.na(row_vals[-1])) && row_vals[1] != "") {
      footer_start <- r
      break
    }
  }

  # Body: rows between colnames and footer, excluding empty separator rows
  body_start <- colnames_row_idx + 1L
  body_end <- footer_start - 1L

  if (body_start > body_end) {
    body <- page[0, ]
  } else {
    body <- slice(page, body_start:body_end)
    # Remove empty rows (separators between header and data)
    body <- filter(body, !if_all(everything(), ~ . == "" | is.na(.)))
  }

  list(
    spanner = spanner,
    colnames = col_names,
    body = body
  )
}

#' Detect the cycle length of page signatures
#'
#' Given a character vector of per-page column signatures, find the smallest
#' k such that signatures repeat with period k.
#'
#' @noRd
detect_cycle_length <- function(signatures) {
  n <- length(signatures)
  for (k in seq_len(n)) {
    pattern <- signatures[seq_len(k)]
    matches <- all(
      vapply(
        seq_len(n),
        function(i) signatures[i] == pattern[((i - 1) %% k) + 1],
        logical(1)
      )
    )
    if (matches) return(k)
  }
  n
}

#' Build disambiguated column names from colnames and spanner
#'
#' Prefixes stat columns with their spanner label to create unique names.
#'
#' @noRd
build_column_names <- function(col_names, spanner) {
  result <- character(length(col_names))
  for (i in seq_along(col_names)) {
    if (i == 1) {
      result[i] <- if (col_names[i] == "" || is.na(col_names[i])) {
        " "
      } else {
        col_names[i]
      }
    } else if (col_names[i] == "" || is.na(col_names[i])) {
      result[i] <- NA_character_
    } else if (spanner[i] != "" && !is.na(spanner[i])) {
      result[i] <- paste0(spanner[i], ": ", col_names[i])
    } else {
      result[i] <- col_names[i]
    }
  }
  result
}

#' Multi-structure pagination
#'
#' Handles tables where pages cycle between different column structures.
#' Groups pages into batches matching the cycle, builds disambiguated column
#' names, and joins pages within each batch on the row-label column.
#'
#' @noRd
paginate_multi_structure <- function(parsed_pages, signatures) {
  cycle_length <- detect_cycle_length(signatures)
  n_pages <- length(parsed_pages)

  # Build column-name templates from the first cycle
  templates <- lapply(seq_len(cycle_length), function(k) {
    build_column_names(parsed_pages[[k]]$colnames, parsed_pages[[k]]$spanner)
  })

  # Identify which columns to keep per template (non-NA names)
  keep_cols <- lapply(templates, function(t) which(!is.na(t)))

  # Group pages into batches
  batch_ids <- ((seq_len(n_pages) - 1) %/% cycle_length) + 1
  n_batches <- max(batch_ids)

  batch_results <- lapply(seq_len(n_batches), function(b) {
    page_indices <- which(batch_ids == b)
    # Position within the cycle for each page in this batch
    cycle_positions <- ((page_indices - 1) %% cycle_length) + 1

    # Process first page in batch
    first_pos <- cycle_positions[1]
    first_page <- parsed_pages[[page_indices[1]]]
    first_names <- templates[[first_pos]]
    first_keep <- keep_cols[[first_pos]]

    first_body <- first_page$body
    if (nrow(first_body) == 0) {
      return(NULL)
    }

    # Apply column names and subset
    first_body <- first_body[, first_keep, drop = FALSE]
    names(first_body) <- first_names[first_keep]

    result <- first_body

    # Join remaining pages in the batch
    if (length(page_indices) > 1) {
      for (j in 2:length(page_indices)) {
        pos <- cycle_positions[j]
        pg <- parsed_pages[[page_indices[j]]]
        pg_names <- templates[[pos]]
        pg_keep <- keep_cols[[pos]]

        pg_body <- pg$body
        if (nrow(pg_body) == 0) {
          next
        }

        pg_body <- pg_body[, pg_keep, drop = FALSE]
        names(pg_body) <- pg_names[pg_keep]

        # Join on the row-label column (first column)
        label_col <- names(result)[1]
        result <- suppressMessages(
          left_join(result, pg_body, by = label_col)
        )
      }
    }

    result
  })

  # Combine all batches and deduplicate
  batch_results <- Filter(Negate(is.null), batch_results)
  result <- bind_rows(batch_results) |>
    distinct()

  # Clean whitespace from the label column
  result
}

#' Replace non-breaking spaces with spaces
#'
#' Convert indentation identified by "&nbsp;" (create via
#' `rtf_spaces_to_nbsp()`) with empty spaces (e.g., " ").
#'
#' @param data A data frame generated by calling [strip_pagination()] containing
#' indentation in the first column, represented by "&nbsp;" values in each cell.
#'
#' @return A data frame with all isntances of "&nbsp;" replaced by empty spaces
#' (e.g., " ").
#'
#' @autoglobal
#' @keywords internal
nbsp_to_spaces <- function(data) {
  data |>
    mutate(
      across(
        everything(),
        ~ stringr::str_replace_all(.x, "&nbsp;|nbsp;", " ")
      )
    )
}

#' Clean whitespace
#'
#' Many parsed columns contain excess whitespace, which often isn't wanted.
#'
#' @param data dataframe
#' @param cols index of columns to clean
#'
#' @noRd
clean_whitespace <- function(data, cols) {
  data |>
    mutate(
      across(
        {{ cols }},
        ~ stringr::str_squish(.x) |>
          stringr::str_replace_all("\\(\\s+", "(")
      )
    )
}

#' Convert indentation to variable cols
#'
#' Unlike `strip_indentation(), this function is designed to be called after a
#' dataframe has been generated from an RTF instead of during the generation.
#' In effect this function pivots a data frame wider, using indentation to infer
#' how the pivoting should happen.
#'
#' @export
#' @autoglobal
#'
#' @examples
#' \dontrun{
#' indentation_to_variables(rtf_to_df(rtf_example(13)))
#' }
indentation_to_variables <- function(data) {
  # Save the original first column name
  # If empty, use a single space for proper rendering
  original_col_name <- names(data)[1]
  if (original_col_name == "") {
    original_col_name <- " "
  }

  indents <- data |>
    mutate(
      space_count = stringr::str_length(stringr::str_extract(data[[1]], "^ *"))
    ) |>
    mutate(space_group = cumsum(space_count == 0)) |>
    mutate(
      counter = case_when(
        space_count == 0 ~ 0,
        space_count > lag(space_count, default = 0) ~ 1,
        space_count == lag(space_count, default = 0) ~ 0,
        space_count < lag(space_count, default = 0) ~ -1
      )
    ) |>
    mutate(indent_level = cumsum(counter), .by = space_group)

  indents |>
    rename(value = 1) |>
    mutate(value2 = value) |>
    mutate(variable_label = paste0(".variable_", indent_level + 1)) |>
    clean_whitespace(cols = where(is.character)) |>
    mutate(id = row_number()) |> # prevents `pivot_wider()` errors caused by duplicate values
    pivot_wider(
      names_from = variable_label,
      values_from = value,
      id_cols = everything()
    ) |>
    group_by(space_group) |>
    fill(starts_with(".variable_")) |>
    ungroup() |>
    mutate(.indent = indent_level) |>
    mutate(!!original_col_name := value2) |>
    select(-space_count:-id) |>
    select(!!original_col_name, everything(), starts_with("."))
}


#' Strip indentation
#'
#' Convert indentation identified by "&nbsp;" values into a series of
#' `variable_*` columns.
#'
#' @param data A data frame generated by calling [strip_pagination()] containing
#' indentation in the first column, represented by "&nbsp;" values in each cell.
#'
#' @return A data frame where the indented first column has been parsed into
#' separate `variable_*` columns in accordance with the ARD standard.
#'
#' @autoglobal
#' @keywords internal
strip_indentation <- function(data) {
  # Label indentation levels
  indents <- data |>
    mutate(
      nbsp_count = stringr::str_count(data[[1]], stringr::fixed("&nbsp;"))
    ) |>
    mutate(nbsp_group = cumsum(nbsp_count == 0)) |>
    mutate(
      counter = case_when(
        nbsp_count == 0 ~ 0,
        nbsp_count > lag(nbsp_count, default = 0) ~ 1,
        nbsp_count == lag(nbsp_count, default = 0) ~ 0,
        nbsp_count < lag(nbsp_count, default = 0) ~ -1
      )
    ) |>
    mutate(indent_level = cumsum(counter), .by = nbsp_group) |>
    mutate(
      indent_level_rev = max(indent_level) + min(indent_level) - indent_level,
      .by = nbsp_group
    )

  # Create `variable_*` columns corresponding to indentation
  variable_cols <- indents |>
    rename(value = 1) |>
    mutate(variable_label = paste0("variable_label", indent_level_rev)) |>
    mutate(id = row_number()) |> # prevents `pivot_wider()` errors caused by duplicate values
    pivot_wider(
      names_from = variable_label,
      values_from = value,
      id_cols = everything()
    ) |>
    group_by(nbsp_group) |>
    fill(starts_with("variable_label")) |>
    ungroup() |>
    rename(variable_level = variable_label0)

  # Clean up
  variable_cols |>
    select(
      variable_level,
      starts_with("variable_label"),
      everything(),
      -id,
      -nbsp_count,
      -nbsp_group,
      -counter,
      -indent_level,
      -indent_level_rev
    ) |>
    mutate(
      across(
        everything(),
        ~ stringr::str_replace_all(., stringr::fixed("&nbsp;"), "")
      )
    )
}

#' Pivot a grouping variable longer
#'
#' The grouping variables in the final ARD are normally presented in a wide
#' format in the input RTF table. This functions pivots the grouping levels into
#' a long format.
#'
#' @param data A data frame with the grouping variable in a wide format.
#'
#' @return A data frame with the grouping variable in a long format.
#'
#' @keywords internal
pivot_group <- function(data) {
  data |>
    rename(variable_level = 1) |>
    pivot_longer(
      !starts_with("variable_"),
      names_to = "group1_level",
      values_to = "stat"
    ) |>
    mutate(group1 = "TRT", .before = 1) |>
    select(starts_with("group"), starts_with("variable"), starts_with("stat"))
}

#' Separate the Big N stat
#'
#' Extract the Big N stat and place it at the top of a table.
#'
#' @param data A data frame containing a column called "group1_level" which
#' contains the Big N statistic merged as part of the text.
#'
#' @return A data frame with the Big N stat separated and placed at the top.
#'
#' @autoglobal
#' @keywords internal
separate_bign <- function(data) {
  big_n <- data |>
    distinct(group1_level) |>
    separate_wider_regex(
      group1_level,
      patterns = c(
        variable_label1 = ".*?\\S+",
        "\\s+",
        "(?:\\(N = |N = )",
        stat = "\\d+",
        "\\)?"
      )
    ) |>
    mutate(stat_name = "N_header", stat_label = "N", .before = "stat")

  data <- data |>
    mutate(
      group1_level = stringr::str_extract(
        group1_level,
        ".*?\\S+(?=\\s*(?:\\(N = |N = ))"
      )
    )

  bind_rows(big_n, data) |>
    select(starts_with("group"), starts_with("variable"), starts_with("stat"))
}

#' Separate a merged columns into multiple columns
#'
#' This function separates columns containing merged values (e.g., where a count
#' and percentage are merged into a single string such as "34 (.56)") into
#' multiple columns inside a data frame generated by calling [rtf_to_html()].
#'
#' @param data A data frame generated by calling [rtf_to_html()].
#'
#' @return A data frame where merged columns have been separated.
#'
#' @keywords internal
separate_merges <- function(data) {
  # Placeholder
}

#' Separate a spanner
#'
#' This function separates spanning column labels out inside a data frame
#' generated by calling [rtf_to_html()]. A spanning column header represents a
#' unique grouping identifier for the columns it spans over.
#'
#' @param data A data frame generated by calling [rtf_to_html()].
#'
#' @return A data frame where merged columns have been separated.
#'
#' @keywords internal
separate_spanners <- function(data) {
  # Placeholder
}

#' Manage table expcetions
#'
#' Several tables do not align with the general ruleset and must be treated as
#' exceptions that get special processing to re-align them.
#'
#' @keywords internal
manage_exceptions <- function(data) {
  if (
    data[[1]][[1]] ==
      "Table 14.1.4.1Baseline Disease Characteristics SummaryRandomized Population"
  ) {
    result <- map_dfr(
      .x = 1:nrow(data),
      .f = \(x) {
        current_row <- as.character(data[x, ])
        if (identical(current_row, as.character(data[2L, ]))) {
          shifted <- c("", current_row[-length(current_row)])
        } else {
          shifted <- current_row
        }
        tibble(!!!set_names(shifted[-2L], names(data)[-2L]))
      }
    )
    return(result)
  } else {
    return(data)
  }
}
